ADGroup: Changing group membership management mechanism
dsccommunity/ActiveDirectoryDsc pull request #620
Opened 2020-07-16 00:07 UTC by jeremyciak

#### Pull Request (PR) description

This Pull Request is intended to change the way that the `ADGroup` resource manages group membership. The new implementation abandons usage of `Add-ADGroupMember` and `Remove-ADGroupMember` due to limitations with **Foreign Security Principals**. Instead we opt to utilize `Set-ADGroup` with the *Add* and *Remove* parameters, passing a hash object with the **member** key and a list of formatted **SID** values (e.g. - `"<SID=SID_VALUE>"`).

- Fixes #619 
#### Task list

- [ ] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2020-07-16 01:00 UTC, jeremyciak commented
There is a lot going on here so please bring on the commentary and suggestions. Also, my unit tests were mostly focused on code coverage so if there are some other tests that should be added please chime in.

2020-07-19 17:27 UTC, X-Guardian commented
@jeremyciak, you have used the master branch in your forked repository again. This makes it more difficult for me to review, because I can't add your fork as another remote in my local Git and switch to this branch, as it conflicts with the standard master branch. Please in future create a branch on your fork with a unique name and use that in your pull request. Thanks.

2020-07-19 17:41 UTC, jeremyciak commented
@X-Guardian, please refer to #621 instead as it is off of a branch from my fork. Sorry!

2020-07-19 22:34 UTC, X-Guardian commented
You have confused Reviewable having the two PR's with the same name, so please stick with one .

2020-08-13 19:30 UTC, X-Guardian commented
@jeremyciak, are you able to make the requested changes to this PR?

2020-08-15 02:07 UTC, jeremyciak commented
Yes, I have been working on these changes lately. Work has picked up significantly for me in the past 2 weeks which has diminished the amount of time I can allocate on this. I have some functional code close to ready but I'm having to get over the hump of some unit test stuff still. Hopefully I can poke at it a bit over the weekend.

2020-08-16 02:06 UTC, jeremyciak commented
@X-Guardian I'm trying to push my changes and the Pipeline does not seem to be getting triggered. Is that because of the CHANGELOG.md conflict that has cropped up now? I'm unable to resolve this conflict. Please let me know what needs to be done. Thanks!

2020-08-16 08:59 UTC, X-Guardian commented
Hi @jeremyciak, you need to resolve the conflicts on `CHANGELOG.md` through Git. You can do this through the GitHub web interface or through the Git command line. I assume you haven't done this before, so have a read of [Addressing merge conflicts](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/addressing-merge-conflicts). Ask if you have any questions.

2020-08-16 13:33 UTC, jeremyciak commented
I followed [these](https://stackoverflow.com/questions/38949951/how-to-solve-merge-conflicts-across-forks) instructions and it looks like it worked. The build appears to be processing now.

2020-08-23 17:22 UTC, X-Guardian requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620)* status: 3 of 12 files reviewed, 25 unresolved discussions (waiting on @jeremyciak and @X-Guardian)

___
*[source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1, line 2616 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFQh3HTBpr3CWzlXm2F:-MFQh3HTBpr3CWzlXm2G:b-7ouw2z) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1#L2616)):*
> ```PowerShell
>     begin
>     {
>         $verbose = $PSBoundParameters.Verbose -eq $true
> ```

This line is not longer need.
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 2292 at r7](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MF-QWQ9Dy9VA-zSxPK4:-MFRH7074nUX4ytroFJy:bvcavew) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/d8bbba5bc9150f14d7d716c59f5810329256059c/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L2292)):*
<details><summary><i>Previously, jeremyciak (Jeremy Ciak) wrote…</i></summary><blockquote>

I use this mock to increment the `memberIndex` so that I can pass an array of members into `Resolve-MembersSecurityIdentifier` and correctly maintain the index through the looping within.
</blockquote></details>

If I comment out the line the tests still pass, so it is not achieving anything.
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 31 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR7KsRAj7E88_VhfEN:-MFR7KsRAj7E88_VhfEO:b6rgat0) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L31)):*
> ```PowerShell
>     Set-StrictMode -Version 1.0
> 
>     $mockADGroupMembersAsADObjects = @(
> ```

As there are some many differing functions to test in this module, can we not share test variables between the tests, but duplicate and move the variables into the `Describe` block for each test that uses them.
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 799 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR4-EQ79aXZRQokIQ8:-MFR4-ERB28Cv9-KpYXl:blodpm1) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L799)):*
> ```PowerShell
> 
>         Mock -CommandName Resolve-MembersSecurityIdentifier -MockWith {
>             return $membershipSID['member']
> ```

No need for `return and please format as:

```powershell
        Mock -CommandName Resolve-MembersSecurityIdentifier `
            -MockWith { $membershipSID['member'] }
```
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 813 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR4Lrm-9ZrkLaBt21h:-MFR4Lrm-9ZrkLaBt21i:bivekw5) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L813)):*
> ```PowerShell
>                 Set-ADCommonGroupMember @setADCommonGroupMemberParms
> 
>                 Assert-MockCalled -CommandName Assert-Module
> ```

Please add `-Exactly -Times 1`
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 814 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR4S5C3lEHi_TaUPZG:-MFR4S5C3lEHi_TaUPZH:b-pnlz5o) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L814)):*
> ```PowerShell
> 
>                 Assert-MockCalled -CommandName Assert-Module
>                 Assert-MockCalled -CommandName Resolve-MembersSecurityIdentifier
> ```

Please add `-Exactly -Times $setADCommonGroupMemberParms.Members.Count`
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 817 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR4ZAr6Q_VuwGPk0xi:-MFR4ZAr6Q_VuwGPk0xj:b-i3ciny) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L817)):*
> ```PowerShell
>                 Assert-MockCalled -CommandName Set-ADGroup -ParameterFilter {
>                     $Add -ne $null
>                 } -Exactly -Times 1
> ```

Please format as:

```powershell
                Assert-MockCalled -CommandName Set-ADGroup `
                    -ParameterFilter { $Add -ne $null } `
                    -Exactly -Times 1
```
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 832 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR59Kh-PvbTJt3HCo7:-MFR59Ki1V-ocI2AgUm3:bivekw5) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L832)):*
> ```PowerShell
>                 Set-ADCommonGroupMember @setADCommonGroupMemberParms
> 
>                 Assert-MockCalled -CommandName Assert-Module
> ```

Please add `-Exactly -Times 1`
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 833 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR5Kwz0Nd3UT6rkbmv:-MFR5Kwz0Nd3UT6rkbmw:b-pnlz5o) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L833)):*
> ```PowerShell
> 
>                 Assert-MockCalled -CommandName Assert-Module
>                 Assert-MockCalled -CommandName Resolve-MembersSecurityIdentifier
> ```

Please add `-Exactly -Times $setADCommonGroupMemberParms.Members.Count`
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 836 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR5QB30gHKV7Igqws9:-MFR5QB30gHKV7IgqwsA:b-aanj4n) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L836)):*
> ```PowerShell
>                 Assert-MockCalled -CommandName Set-ADGroup -ParameterFilter {
>                     $Remove -ne $null
>                 } -Exactly -Times 1
> ```

Please format as:

```powershell
                Assert-MockCalled -CommandName Set-ADGroup `
                    -ParameterFilter { $Remove -ne $null } `
                    -Exactly -Times 1
```
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 840 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR5VwS7NvhB6vnNtVe:-MFR5VwS7NvhB6vnNtVf:b9tpd7f) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L840)):*
> ```PowerShell
>         }
> 
>         Context "When 'Set-ADGroup' fails" {
> ```

Please change to `When 'Set-ADGroup' throw an exception`
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 843 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR5oKMB93QJXw_cRaf:-MFR5oKMB93QJXw_cRag:bcgzt72) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L843)):*
> ```PowerShell
>             BeforeAll {
>                 Mock -CommandName Set-ADGroup -MockWith {
>                     throw (New-Guid).Guid
> ```

Please change to `throw 'Error'`
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 844 at r8](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFR6a9OB4KdIdtMuBic:-MFR6a9OB4KdIdtMuBid:b-3shown) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/dc99995f682553d8e8afca18d34f855f2f21f809/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L844)):*
> ```PowerShell
>                 Mock -CommandName Set-ADGroup -MockWith {
>        [...]

2020-08-25 13:40 UTC, jeremyciak commented
@X-Guardian, I just want to double check that this is not waiting on me because last time I assumed it wasn't I was wrong and it just sat for a week until I realized that was the case.

2020-08-25 15:44 UTC, X-Guardian commented
Hi @jeremyciak, yes it is with me. You can see by looking at the `reviewable` check, and it tells you who the discussions are pending with.

2020-08-25 16:03 UTC, jeremyciak commented
Alright awesome, thanks!

2020-09-11 04:37 UTC, jeremyciak commented
@X-Guardian do you think you will have any bandwidth to circle back on this over the weekend?

2020-09-27 17:01 UTC, X-Guardian commented
___
*[tests/Unit/MSFT_ADGroup.Tests.ps1, line 756 at r9](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MFZOl1W1Uki6ojqM0nS:-MFZOl1W1Uki6ojqM0nT:b-rs9qhc) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/fb5954473d81366a13ccab127ea33bb01a5f72fc/tests/Unit/MSFT_ADGroup.Tests.ps1#L756)):*
> ```PowerShell
>                 Assert-MockCalled -CommandName Set-ADCommonGroupMember -ParameterFilter {
>                     $Action -eq 'Add'
>                 } -Scope It -Exactly -Times 1
> ```

Can we format the `Assert-MockCalled` as:

```powershell
Assert-MockCalled -CommandName Set-ADCommonGroupMember `
    -ParameterFilter { $Action -eq 'Add' } `
    -Scope It -Exactly -Times 1
```

here and below to keep the indentation correct.


<!-- Sent from Reviewable.io -->

2020-09-27 17:04 UTC, X-Guardian commented
___
*[tests/Unit/MSFT_ADGroup.Tests.ps1, line 890 at r9](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MIFW0kc4SY0RMhdzXZD:-MIFW0kc4SY0RMhdzXZE:b-s6nhsc) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/fb5954473d81366a13ccab127ea33bb01a5f72fc/tests/Unit/MSFT_ADGroup.Tests.ps1#L890)):*
> ```PowerShell
>                 Mock -CommandName Set-ADCommonGroupMember -ParameterFilter {
>                     $Action -eq 'Add'
>                 }
> ```

Can we format this as:

```powershell
Mock -CommandName Set-ADCommonGroupMember `
    -ParameterFilter { $Action eq - 'Add' }
```

here and below to keep the indentation correct.


<!-- Sent from Reviewable.io -->

2020-09-27 17:53 UTC, X-Guardian requested changes
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620)* status: 3 of 12 files reviewed, 4 unresolved discussions (waiting on @jeremyciak and @X-Guardian)

___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 751 at r9](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MIFflDk4mbamqGBlmd-:-MIFflDl18zx7lgiEvFZ:bw02d9y) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/fb5954473d81366a13ccab127ea33bb01a5f72fc/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L751)):*
> ```PowerShell
>     }
> 
>     Describe 'ActiveDirectoryDsc.Common\Set-ADCommonGroupMember' {
> ```

Here is a refactored/reformatted `Set-ADCommonGroupMember` test:

```powershell
Describe 'ActiveDirectoryDsc.Common\Set-ADCommonGroupMember' {
        BeforeAll {
            $mockADGroupMembersAsADObjects = @(
                [PSCustomObject] @{
                    DistinguishedName = 'CN=User 1,CN=Users,DC=contoso,DC=com'
                    ObjectGUID        = 'a97cc867-0c9e-4928-8387-0dba0c883b8e'
                    SamAccountName    = 'USER1'
                    ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-1106'
                    ObjectClass       = 'user'
                }
                [PSCustomObject] @{
                    DistinguishedName = 'CN=Group 1,CN=Users,DC=contoso,DC=com'
                    ObjectGUID        = 'e2328767-2673-40b2-b3b7-ce9e6511df06'
                    SamAccountName    = 'GROUP1'
                    ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-1206'
                    ObjectClass       = 'group'
                }
                [PSCustomObject] @{
                    DistinguishedName = 'CN=Computer 1,CN=Users,DC=contoso,DC=com'
                    ObjectGUID        = '42f9d607-0934-4afc-bb91-bdf93e07cbfc'
                    SamAccountName    = 'COMPUTER1'
                    ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-6606'
                    ObjectClass       = 'computer'
                }
                # This entry is used to represent a group member from a one-way trusted domain
                [PSCustomObject] @{
                    DistinguishedName = 'CN=S-1-5-21-8562719340-2451078396-046517832-2106,CN=ForeignSecurityPrincipals,DC=contoso,DC=com'
                    ObjectGUID        = '6df78e9e-c795-4e67-a626-e17f1b4a0d8b'
                    SamAccountName    = 'ADATUM\USER1'
                    ObjectSID         = 'S-1-5-21-8562719340-2451078396-046517832-2106'
                    ObjectClass       = 'foreignSecurityPrincipal'
                }
            )

            $setADCommonGroupMemberParms = @{
                Members             = $mockADGroupMembersAsADObjects.DistinguishedName
                MembershipAttribute = 'DistinguishedName'
                Parameters          = @{
                    Identity = 'CN=TestGroup,OU=Fake,DC=contoso,DC=com'
                }
            }

            $membershipSID = @{
                member = $mockADGroupMembersAsADObjects.ObjectSID | ForEach-Object -Process { "<SID=$($_)>" }
            }

            Mock -CommandName Assert-Module
            Mock -CommandName Resolve-MembersSecurityIdentifier -MockWith { $membershipSID['member'] }
            Mock -CommandName Set-ADGroup
        }

        Context "When the 'Action' parameter is specified as 'Add'" {
            BeforeAll {
                $setADCommonGroupMemberAddParms = $setADCommonGroupMemberParms.Clone()
                $setADCommonGroupMemberAddParms['Action'] = 'Add'
            }

            It 'Should not throw' {
                { Set-ADCommonGroupMember @setADCommonGroupMemberAddParms } | Should -Not -Throw
            }

            It 'Should call the expected mocks' {
                Assert-MockCalled -CommandName Assert-Module `
                    -ParameterFilter { $ModuleName -eq 'ActiveDirectory' } `
                    -Exactly -Times 1
                Assert-MockCalled -CommandName Resolve-MembersSecurityIdentifier `
                    -Exactly -Times $setADCommonGroupMemberAddParms.Members.Count
                Assert-MockCalled -CommandName Set-ADGroup `
                    -ParameterFilter { `
                        $Add -ne $null -and `
                        $Identity -eq $setADCommonGroupMemberAddParms.Parameters.Identity } `
                    -Exactly -Times 1
            }
        }

        Context "When 'Action' parameter is specified as 'Remove'" {
            BeforeAll {
                $setADCommonGroupMemberRemoveParms = $setADCommonGroupMemberParms.Clone()
                $setADCommonGroupMemberRemoveParms['Action'] = 'Remove'
            }

            It 'Should not throw' {
                { Set-ADCommonGroupMember @setADCommonGroupMemberRemoveParms } | Should -Not -Throw
            }

            It 'Should call the expected mocks' {
                Assert-MockCalled -CommandName Assert-Module `
                    -ParameterFilter { $ModuleName -eq 'ActiveDirectory' } `
                    -Exactly -Times 1
                Assert-MockCalled -CommandName Resolve-MembersSecurityIdentifier `
                    -Exactly -Times $setADCommonGroupMemberRemoveParms.Members.Count
                Assert-MockCalled -CommandName Set-ADGroup `
                    -ParameterFilter { `
                        $Remove -ne $null -and `
                        $Identity -eq $setADCommonGroupMemberRemoveParms.Parameters.Identity } `
                    -Exactly -Times 1
            }
        }

        Context "When 'Set-ADGroup' throws an exception" {
            BeforeAll {
                Mock -CommandName Set-ADGroup -MockWith { throw 'Error' }

                $errorMessage = $script:localizedData.FailedToSetADGroupMembership -f
                    $setADCommonGroupMemberParms.Parameters.Identity
            }

            It "Should throw the correct exception" {
                { Set-ADCommonGroupMember @setADCommonGroupMemberParms } |
                    Should -Throw $errorMessage
            }
        }
    }
```
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 2137 at r9](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MIFgFOL-H4IrEyq6E3R:-MIFgFOL-H4IrEyq6E3S:bu0o8h3) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/fb5954473d81366a13ccab127ea33bb01a5f72fc/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L2137)):*
> ```PowerShell
>     }
> 
>     Describe 'ActiveDirectoryDsc.Common\Resolve-MembersSecurityIdentifier' {
> ```

Here is a refactored/reformatted `Resolve-MembersSecurityIdentifier` test:

```powershell
Describe 'ActiveDirectoryDsc.Common\Resolve-MembersSecurityIdentifier' {
        $mockADGroupMembersAsADObjects = @(
            [PSCustomObject] @{
                DistinguishedName = 'CN=User 1,CN=Users,DC=contoso,DC=com'
                ObjectGUID        = 'a97cc867-0c9e-4928-8387-0dba0c883b8e'
                SamAccountName    = 'USER1'
                ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-1106'
                ObjectClass       = 'user'
            }
            [PSCustomObject] @{
                DistinguishedName = 'CN=Group 1,CN=Users,DC=contoso,DC=com'
                ObjectGUID        = 'e2328767-2673-40b2-b3b7-ce9e6511df06'
                SamAccountName    = 'GROUP1'
                ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-1206'
                ObjectClass       = 'group'
            }
            [PSCustomObject] @{
                DistinguishedName = 'CN=Computer 1,CN=Users,DC=contoso,DC=com'
                ObjectGUID        = '42f9d607-0934-4afc-bb91-bdf93e07cbfc'
                SamAccountName    = 'COMPUTER1'
                ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-6606'
                ObjectClass       = 'computer'
            }
            # This entry is used to represent a group member from a one-way trusted domain
           [...]

2020-09-27 18:06 UTC, X-Guardian commented
Can you add an example ADGroup resource file with the qualified SamAccountName name format required for one way external trusts. Something like the following:

```powershell
<#PSScriptInfo
.VERSION 1.0.0
.GUID f2ecc331-e242-4204-a6b1-54fd68c852b7
.AUTHOR DSC Community
.COMPANYNAME DSC Community
.COPYRIGHT DSC Community contributors. All rights reserved.
.TAGS DSCConfiguration
.LICENSEURI https://github.com/dsccommunity/ActiveDirectoryDsc/blob/master/LICENSE
.PROJECTURI https://github.com/dsccommunity/ActiveDirectoryDsc
.ICONURI https://dsccommunity.org/images/DSC_Logo_300p.png
.RELEASENOTES
Initial release
#>

#Requires -Module ActiveDirectoryDsc

<#
    .DESCRIPTION
        This configuration will create a new domain-local group in contoso with
        two members; one from the contoso domain and one from the fabrikam domain.
        This qualified SamAccountName format is required if any of the users are in a 
        one-way trusted forest/external domain.
#>
Configuration ADGroup_NewGroupOneWayTrust_Config
{
    Import-DscResource -ModuleName ActiveDirectoryDsc

    node localhost
    {
        ADGroup 'ExampleExternalTrustGroup'
        {
            GroupName           = 'ExampleExternalTrustGroup'
            GroupScope          = 'DomainLocal'
            MembershipAttribute = 'SamAccountName'
            Members             = @(
                'contoso\john'
                'fabrikam\toby'
            )
        }
    }
}
```






<!-- Sent from Reviewable.io -->

2020-10-03 15:05 UTC, jeremyciak reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620)* status: 3 of 13 files reviewed, 4 unresolved discussions (waiting on @X-Guardian)

___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 751 at r9](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MIFflDk4mbamqGBlmd-:-MIiwRyD1e_d05ritmSV:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/fb5954473d81366a13ccab127ea33bb01a5f72fc/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L751)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Here is a refactored/reformatted `Set-ADCommonGroupMember` test:

```powershell
Describe 'ActiveDirectoryDsc.Common\Set-ADCommonGroupMember' {
        BeforeAll {
            $mockADGroupMembersAsADObjects = @(
                [PSCustomObject] @{
                    DistinguishedName = 'CN=User 1,CN=Users,DC=contoso,DC=com'
                    ObjectGUID        = 'a97cc867-0c9e-4928-8387-0dba0c883b8e'
                    SamAccountName    = 'USER1'
                    ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-1106'
                    ObjectClass       = 'user'
                }
                [PSCustomObject] @{
                    DistinguishedName = 'CN=Group 1,CN=Users,DC=contoso,DC=com'
                    ObjectGUID        = 'e2328767-2673-40b2-b3b7-ce9e6511df06'
                    SamAccountName    = 'GROUP1'
                    ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-1206'
                    ObjectClass       = 'group'
                }
                [PSCustomObject] @{
                    DistinguishedName = 'CN=Computer 1,CN=Users,DC=contoso,DC=com'
                    ObjectGUID        = '42f9d607-0934-4afc-bb91-bdf93e07cbfc'
                    SamAccountName    = 'COMPUTER1'
                    ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-6606'
                    ObjectClass       = 'computer'
                }
                # This entry is used to represent a group member from a one-way trusted domain
                [PSCustomObject] @{
                    DistinguishedName = 'CN=S-1-5-21-8562719340-2451078396-046517832-2106,CN=ForeignSecurityPrincipals,DC=contoso,DC=com'
                    ObjectGUID        = '6df78e9e-c795-4e67-a626-e17f1b4a0d8b'
                    SamAccountName    = 'ADATUM\USER1'
                    ObjectSID         = 'S-1-5-21-8562719340-2451078396-046517832-2106'
                    ObjectClass       = 'foreignSecurityPrincipal'
                }
            )

            $setADCommonGroupMemberParms = @{
                Members             = $mockADGroupMembersAsADObjects.DistinguishedName
                MembershipAttribute = 'DistinguishedName'
                Parameters          = @{
                    Identity = 'CN=TestGroup,OU=Fake,DC=contoso,DC=com'
                }
            }

            $membershipSID = @{
                member = $mockADGroupMembersAsADObjects.ObjectSID | ForEach-Object -Process { "<SID=$($_)>" }
            }

            Mock -CommandName Assert-Module
            Mock -CommandName Resolve-MembersSecurityIdentifier -MockWith { $membershipSID['member'] }
            Mock -CommandName Set-ADGroup
        }

        Context "When the 'Action' parameter is specified as 'Add'" {
            BeforeAll {
                $setADCommonGroupMemberAddParms = $setADCommonGroupMemberParms.Clone()
                $setADCommonGroupMemberAddParms['Action'] = 'Add'
            }

            It 'Should not throw' {
                { Set-ADCommonGroupMember @setADCommonGroupMemberAddParms } | Should -Not -Throw
            }

            It 'Should call the expected mocks' {
                Assert-MockCalled -CommandName Assert-Module `
                    -ParameterFilter { $ModuleName -eq 'ActiveDirectory' } `
                    -Exactly -Times 1
                Assert-MockCalled -CommandName Resolve-MembersSecurityIdentifier `
                    -Exactly -Times $setADCommonGroupMemberAddParms.Members.Count
                Assert-MockCalled -CommandName Set-ADGroup `
                    -ParameterFilter { `
                        $Add -ne $null -and `
                        $Identity -eq $setADCommonGroupMemberAddParms.Parameters.Identity } `
                    -Exactly -Times 1
            }
        }

        Context "When 'Action' parameter is specified as 'Remove'" {
            BeforeAll {
                $setADCommonGroupMemberRemoveParms = $setADCommonGroupMemberParms.Clone()
                $setADCommonGroupMemberRemoveParms['Action'] = 'Remove'
            }

            It 'Should not throw' {
                { Set-ADCommonGroupMember @setADCommonGroupMemberRemoveParms } | Should -Not -Throw
            }

            It 'Should call the expected mocks' {
                Assert-MockCalled -CommandName Assert-Module `
                    -ParameterFilter { $ModuleName -eq 'ActiveDirectory' } `
                    -Exactly -Times 1
                Assert-MockCalled -CommandName Resolve-MembersSecurityIdentifier `
                    -Exactly -Times $setADCommonGroupMemberRemoveParms.Members.Count
                Assert-MockCalled -CommandName Set-ADGroup `
                    -ParameterFilter { `
                        $Remove -ne $null -and `
                        $Identity -eq $setADCommonGroupMemberRemoveParms.Parameters.Identity } `
                    -Exactly -Times 1
            }
        }

        Context "When 'Set-ADGroup' throws an exception" {
            BeforeAll {
                Mock -CommandName Set-ADGroup -MockWith { throw 'Error' }

                $errorMessage = $script:localizedData.FailedToSetADGroupMembership -f
                    $setADCommonGroupMemberParms.Parameters.Identity
            }

            It "Should throw the correct exception" {
                { Set-ADCommonGroupMember @setADCommonGroupMemberParms } |
                    Should -Throw $errorMessage
            }
        }
    }
```
</blockquote></details>

Done.
___
*[tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1, line 2137 at r9](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620#-MIFgFOL-H4IrEyq6E3R:-MIiwo_30Nt47PApJuGM:b-896fix) ([raw file](https://github.com/dsccommunity/activedirectorydsc/blob/fb5954473d81366a13ccab127ea33bb01a5f72fc/tests/Unit/ActiveDirectoryDsc.Common.Tests.ps1#L2137)):*
<details><summary><i>Previously, X-Guardian (Simon Heather) wrote…</i></summary><blockquote>

Here is a refactored/reformatted `Resolve-MembersSecurityIdentifier` test:

```powershell
Describe 'ActiveDirectoryDsc.Common\Resolve-MembersSecurityIdentifier' {
        $mockADGroupMembersAsADObjects = @(
            [PSCustomObject] @{
                DistinguishedName = 'CN=User 1,CN=Users,DC=contoso,DC=com'
                ObjectGUID        = 'a97cc867-0c9e-4928-8387-0dba0c883b8e'
                SamAccountName    = 'USER1'
                ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-1106'
                ObjectClass       = 'user'
            }
            [PSCustomObject] @{
                DistinguishedName = 'CN=Group 1,CN=Users,DC=contoso,DC=com'
                ObjectGUID        = 'e2328767-2673-40b2-b3b7-ce9e6511df06'
                SamAccountName    = 'GROUP1'
                ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-1206'
                ObjectClass       = 'group'
            }
            [PSCustomObject] @{
                DistinguishedName = 'CN=Computer 1,CN=Users,DC=contoso,DC=com'
                ObjectGUID        = '42f9d607-0934-4afc-bb91-bdf93e07cbfc'
                SamAccountName    = 'COMPUTER1'
                ObjectSID         = 'S-1-5-21-1131554080-2861379300-292325817-6606'
                ObjectClass       = 'computer'
            }
            # This entry is used to represent a group member from a one-way trusted domain
            [PSCustom [...]

2020-10-10 08:12 UTC, X-Guardian reviewed
> Reviewed 1 of 5 files at r2, 1 of 4 files at r3, 3 of 8 files at r7, 1 of 2 files at r9, 1 of 1 files at r10, 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620)* status: 11 of 13 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-10 08:13 UTC, X-Guardian approved these changes
> Reviewed 2 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/activedirectorydsc/620)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-10 08:15 UTC, X-Guardian commented
Fantastic work @jeremyciak, and thanks for your patience. LGTM!

2020-10-10 08:16 UTC, merged