ADReadOnlyDomainControllerAccount: New resource
dsccommunity/ActiveDirectoryDsc pull request #713
Opened 2024-07-29 12:55 UTC by Borgquite

#### Pull Request (PR) description

As discussed in #711 - a new resource to allow pre-staging of read-only domain controller accounts

#### This Pull Request (PR) fixes the following issues

- Fixes #40
- Fixes #711

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713)

2024-07-29 12:55 UTC, Borgquite commented
Just doing an initial pull to see if this works before I update the tests - leave this with me for now :)

2024-07-29 14:12 UTC, johlju commented
For the build to run, update azure-pipelines.yml according to this: https://github.com/gaelcolas/Sampler/issues/477#issuecomment-2246099769

2024-07-29 14:20 UTC, Borgquite commented
@johlju Love it when you pop out for lunch & the solution's waiting when you return! Ta! :)

2024-07-30 13:22 UTC, Borgquite commented
@johlju This PR is ready for review whenever you are :)

2024-07-30 14:08 UTC, johlju requested changes
Awesome work, just one comment to discuss. 

> Reviewed 4 of 7 files at r1, 1 of 2 files at r3, 8 of 9 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-:-O32y1MY33QxvG-YpIno:bxqgvrp)* status: all files reviewed, 1 unresolved discussion (waiting on @Borgquite)

___
*[`source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1` line 1354 at r5](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O32xfsN8XASl9aHYsmh:-O32xfsN8XASl9aHYsmi:b-hcbncm) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/06455aec5169044002f15e78feb32fff6f06c54d/source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1#L1354)):*
> ```PowerShell
>         $domainControllerObject = Get-ADDomainController @getADDomainControllerParameters
> 
>         if (-not $domainControllerObject -and $env:COMPUTERNAME -eq $ComputerName -and (Test-IsDomainController) -eq $true)
> ```

Not sure about this change, this prevents the command to be called from another computer - feels like a breaking change. Why is it needed? :thinking: 


<!-- Sent from Reviewable.io -->

2024-07-30 15:11 UTC, Borgquite reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1` line 1354 at r5](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O32xfsN8XASl9aHYsmh:-O339NfABakkMl8pAQSW:bdisp24) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/06455aec5169044002f15e78feb32fff6f06c54d/source/Modules/ActiveDirectoryDsc.Common/ActiveDirectoryDsc.Common.psm1#L1354)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not sure about this change, this prevents the command to be called from another computer - feels like a breaking change. Why is it needed? :thinking:
</blockquote></details>

Sure.

TL;DR Get-DomainControllerObject is currently broken when $ComputerName is not $env:COMPUTERNAME, and this fixes it.

--

Get-DomainControllerObject is used by ADDomainController and now ADReadOnlyDomainControllerAccount to find the domain controller object for $ComputerName. Until this change, it's never been used for anything other than $env:COMPUTERNAME (local node) inside ADDomainController - but I'm reusing it in ADReadOnlyDomainControllerAccount.

However, at present, if $ComputerName is set to another name, to check a domain controller other then the local computer, it always fails. This line basically says 'if there is no domain controller account object named $ComputerName, and the local computer is a domain controller, throw an error' (Test-IsDomainController returns true if the local computer is a domain controller). This doesn't make any sense at all if $ComputerName is *not* the local computer - so Get-DomainControllerObject always fails if $env:COMPUTERNAME != $ComputerName. The fix here is not to run Test-IsDomainController if we're running against another computer - which allows the function to be used in ADReadOnlyDomainController as intended.


<!-- Sent from Reviewable.io -->

2024-08-01 10:54 UTC, Borgquite commented
@johlju Let me know if I haven't explained the above very well!

2024-08-08 14:21 UTC, Borgquite commented
@johlju Ping - when you are able!

2024-08-09 11:36 UTC, Borgquite commented
I've updated Get-DomainControllerObject to make the intended fix clearer

2024-08-12 09:35 UTC, PlagueHO requested changes
Hi @Borgquite - great job! I've finished review and just a few minor things.

One thing I always ask: Is it possible to create integration tests for this resource as well? Even if they can't be executed in the Azure DevOps pipeline, being able to run them locally on a node in a test AD would be useful. I haven't kept up with this module, so it's possible that the module doesn't generally keep up this practice - so defer to the usual maintainers :grinning:

> Reviewed 4 of 7 files at r1, 1 of 2 files at r3, 6 of 9 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-:-O44tuX70VeArJ4tXzA2:brl7md5)* status: all files reviewed, 21 unresolved discussions (waiting on @Borgquite and @johlju)

___
*[`CHANGELOG.md` line 23 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44cs4c2gE4SdemHdn9:-O44cs4c2gE4SdemHdnA:b-95akkd) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/CHANGELOG.md#L23)):*
> ```Markdown
> - Update build process to pin GitVersion to 5.* to resolve errors
>   (https://github.com/gaelcolas/Sampler/issues/477).
> ```

Can you also mention the fix to `Get-DomainControllerObject`?
___
*[`source/DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof` line 20 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44dSOCEA3zhvOJOWFF:-O44dSOCEA3zhvOJOWFG:by1jnp0) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof#L20)):*
> ```
>     [Write, Description("Specifies one or more Flexible Single Master Operation (FSMO) roles to move to this domain controller. The current owner must be online and responding for the move to be allowed."), ValueMap{"DomainNamingMaster", "SchemaMaster", "InfrastructureMaster", "PDCEmulator", "RIDMaster"}, Values{"DomainNamingMaster", "SchemaMaster", "InfrastructureMaster", "PDCEmulator", "RIDMaster"}] String FlexibleSingleMasterOperationRole[];
>     [Write, Description("Specifies if the DNS Server service should be installed and configured on the Domain Controller. If this is not set the default value of the parameter `InstallDns` of the cmdlet Install-ADDSDomainController is used. This parameter is only used during the provisioning of a domain controller. The parameter cannot be used to install or uninstall the DNS server on an already provisioned domain controller.")] Boolean InstallDns;
>     [Write, Description("Indicates that the cmdlet attaches a server to an existing Read-Only Domain Controller (RODC) account. If specified, a member of the Domain Admins group or a delegated user can run this cmdlet.")] Boolean UseExistingAccount;
> ```

This seems to refer to a cmdlet. Presumably this should refer to "apply the DSC resource"?



_Code quote:_
```
If specified, a member of the Domain Admins group or a delegated user can run this cmdlet.
```
___
*[`source/DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt` line 106 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44dq2-72oxIlCXQ1uI:-O44dq2-72oxIlCXQ1uJ:b-wkq9h0) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt#L106)):*
> ```help
> .PARAMETER UseExistingAccount
>     Write - Boolean
>     Indicates that the cmdlet attaches a server to an existing Read-Only Domain Controller (RODC) account. If specified, a member of the Domain Admins group or a delegated user can run this cmdlet.
> ```

See previous comment about: "This seems to refer to a cmdlet. Presumably this should refer to "apply the DSC resource"?"
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 99 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44inG239vWyxWkoq_M:-O44inG239vWyxWkoq_N:bresifw) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L99)):*
> ```PowerShell
>         # Retrieve any user or group that is a delegated administrator via the ManagedBy attribute
>         $delegateAdministratorAccountName = $null
>         $domainControllerComputerObject = $domainControllerObject.ComputerObjectDN | Get-ADComputer -Properties ManagedBy -Credential $Credential
> ```

nit: Long line - can this be split at the pipe (I know other resources in this module don't adhere to this - so only a nit)
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 102 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44ixha24VXzcmX1K20:-O44ixha24VXzcmX1K21:bresifw) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L102)):*
> ```PowerShell
>         if ($domainControllerComputerObject.ManagedBy)
>         {
>             $domainControllerManagedByObject = $domainControllerComputerObject.ManagedBy | Get-ADObject -Properties objectSid -Credential $Credential
> ```

nit: Long line - can this be split at the pipe (I know other resources in this module don't adhere to this - so only a nit)
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 107 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44joBU8prapc-lzipD:-O44joBVAD_QwRHON61H:bu6jkft) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L107)):*
> ```PowerShell
>         }
> 
>         $allowedPasswordReplicationAccountName = (
> ```

nit: Are ( ) needed here?
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 110 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44jqPT2wBBvXsOg1tK:-O44jqPT2wBBvXsOg1tL:bu6jkft) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L110)):*
> ```PowerShell
>             Get-ADDomainControllerPasswordReplicationPolicy -Allowed -Identity $domainControllerObject |
>             ForEach-Object -MemberName sAMAccountName)
>         $deniedPasswordReplicationAccountName = (
> ```

nit: Are ( ) needed here?
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 122 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44lzpC8psPmvPObe8q:-O44lzpC8psPmvPObe8r:b-f6evu1) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L122)):*
> ```PowerShell
>             DomainName                          = $domainControllerObject.Domain
>             Ensure                              = $true
>             InstallDns                          = $InstallDns
> ```

Is this value stored with the RODC account? If not, how does it get used when prestaging an RODC account?

I can see that `Add-ADDSReadOnlyDomainControllerAccount` does support the `-InstallDns` parameter, but I can't actually figure out how it would actually work - unless the flag was stored with the AD object.

The reason I'm asking is if the s [...]

2024-08-12 09:35 UTC, PlagueHO reviewed
> Reviewed 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713)* status: all files reviewed, 21 unresolved discussions (waiting on @Borgquite and @johlju)



<!-- Sent from Reviewable.io -->

2024-08-12 11:13 UTC, Borgquite reviewed
In general, the resource is based on ADDomainController - so a lot of my fixes below I've also fixed there, for consistency. For that reason I also haven't done any integration tests - there aren't any for ADDomainController, and I guess that may be due to complexity (you'd have to spin up an existing domain first to be able to do it, a job beyond me!) However because the resource is a copy/paste of a resource that is working well, I hope we can live without it for now.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-:-O45Dg3y5tEGpKpvkbKK:b-5ksxtk)* status: 6 of 17 files reviewed, 15 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[`CHANGELOG.md` line 23 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44cs4c2gE4SdemHdn9:-O44yUdI7a_B9GfmbOJG:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/CHANGELOG.md#L23)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you also mention the fix to `Get-DomainControllerObject`?
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof` line 20 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44dSOCEA3zhvOJOWFF:-O44yz-C0bdQzpLCrE3A:bybyjez) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADDomainController/MSFT_ADDomainController.schema.mof#L20)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This seems to refer to a cmdlet. Presumably this should refer to "apply the DSC resource"?
</blockquote></details>

Yeah - this was a copy/paste from the Install-ADDSDomainController documentation, but I've updated it here, as well as in the help for ReadOnlyReplica above. :)
___
*[`source/DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt` line 106 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44dq2-72oxIlCXQ1uI:-O44zV9b7PitDhA83der:b-896fix) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADDomainController/en-US/about_ADDomainController.help.txt#L106)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

See previous comment about: "This seems to refer to a cmdlet. Presumably this should refer to "apply the DSC resource"?"
</blockquote></details>

Done.
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 107 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44joBU8prapc-lzipD:-O452hb8-VF0VZjNIezv:b-hxl5oh) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L107)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Are ( ) needed here?
</blockquote></details>

Not sure - but this isn't my code (copied from ADDomainController) so reluctant to fiddle as it currently works.
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 110 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44jqPT2wBBvXsOg1tK:-O452oRU2LeEcQ5hbvNq:b-89a4l7) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L110)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

nit: Are ( ) needed here?
</blockquote></details>

Ditto
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 122 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44lzpC8psPmvPObe8q:-O452u889gCKow2oAv6z:bqypkqn) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L122)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is this value stored with the RODC account? If not, how does it get used when prestaging an RODC account?

I can see that `Add-ADDSReadOnlyDomainControllerAccount` does support the `-InstallDns` parameter, but I can't actually figure out how it would actually work - unless the flag was stored with the AD object.

The reason I'm asking is if the state is not stored and able to be retrieved, could we eliminate it entirely - as we're not installing an RODC (and the DNS service), we're just creating the RODC account object.

Sorry if this doesn't make sense (it's been a while since I've dealt with RODC's :grin:)
</blockquote></details>

Ah, this was something that was bugging me too. In my investigations:
* I couldn't see how the switch made any difference to the created AD object (perhaps it does something elsewhere though?)
* HOWEVER when performing the 'other half' of the process (Install-ADDSDomainController -UseExistingAccount), the -InstallDNS parameter is *not* available within the cmdlet parameter set. I therefore think it's important to leave it in, in case it happens to be doing something under the hood somewhere I didn't think to check.
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 288 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44n4STCvVltAhslXZn:-O454FU95wVwWyiwjuJj:b-34vmyd) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L288)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

See previous query regarding InstallDns parameter.
</blockquote></details>

See above
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 398 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44o_6I4LXWLYBVJ17L:-O454T6A5_Kt3mukyL7f:b-hqshqg) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L398)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This block seems to have a lot of similar code to the previous block. Any chance we could split it out into a function and reduce the duplication?
</blockquote></details>

Again, not my code, copied from ADDomainController, so would prefer not to get into this for this patch.
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 477 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44p7V7BJz304WpEprB:-O454XfC-Pvp22cFvgr_:b-34vmyd) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L477)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

See previous query regarding InstallDns
</blockquote></details>

See above
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 609 at r6](https://revie [...]

2024-08-14 09:17 UTC, PlagueHO requested changes
Heh - yeah, I built Labbuilder way back to deal with the problem of integration testing the AD/ADCS DSC resources (got tired of rebuilding DCs).

I was certain I built integration tests for ADDomainController ... but turns out I raised it as an issue to create them in 2016 :D but never got round to it: [Create Integration Tests for Resources · Issue #121 · dsccommunity/ActiveDirectoryDsc (github.com)](https://github.com/dsccommunity/ActiveDirectoryDsc/issues/121) - oops my bad :grinning:

So, yes, can live without for now. 

Thanks again for submitting this! And if you do feel like building integration tests for these (or other resources... there's an open issue :laughing: )

> Reviewed 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-:-O4F8-5K3GVzMhTyr7qQ:b5e9a83)* status: all files reviewed, 3 unresolved discussions (waiting on @Borgquite and @johlju)

___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 107 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44joBU8prapc-lzipD:-O4F0LUh9g6K4HQ6KVqs:b-ymbz13) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L107)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Not sure - but this isn't my code (copied from ADDomainController) so reluctant to fiddle as it currently works.
</blockquote></details>

Sure - leave it as is.
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 122 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44lzpC8psPmvPObe8q:-O4F0Ag3-H4rX5zPyDch:bq8g4o2) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L122)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Ah, this was something that was bugging me too. In my investigations:
* I couldn't see how the switch made any difference to the created AD object (perhaps it does something elsewhere though?)
* HOWEVER when performing the 'other half' of the process (Install-ADDSDomainController -UseExistingAccount), the -InstallDNS parameter is *not* available within the cmdlet parameter set. I therefore think it's important to leave it in, in case it happens to be doing something under the hood somewhere I didn't think to check.
</blockquote></details>

Ok- happy to leave it in - as I expect it's not going to hurt anything. Just wanted to make sure it wasn't some oversight. 
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1` line 398 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44o_6I4LXWLYBVJ17L:-O4F0bnzATIYzhz1zDZA:b-ghpfl1) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/MSFT_ADReadOnlyDomainControllerAccount.psm1#L398)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Again, not my code, copied from ADDomainController, so would prefer not to get into this for this patch.
</blockquote></details>

Is it identical code to the code in ADDomainController I feel like it should be refactored at some point.  I gettit though: keeping ahead of all the refactoring we should do on these is a losing battle :grinning: But it still ok to refactor existing/other code if it makes maintaining easier and reduces the size of the code base.

Could an issue be added to remediate this at some point - e.g. DRY? 
___
*[`tests/Unit/MSFT_ADReadOnlyDomainControllerAccount.Tests.ps1` line 68 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44udLKBpmMSvOa7Vuw:-O4F6aY-0yCNXXJLWxBu:b-9rpmyw) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/tests/Unit/MSFT_ADReadOnlyDomainControllerAccount.Tests.ps1#L68)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Not my code, but happy to update
</blockquote></details>

Thank you - reviewable just showed it as new code. But as maintainer, love to have improved code, even if it's cloned from something else (or even if the original code is refactored as well :grin:) - all just considered code janitorial work (which we need a lot of in these repos).
___
*[`tests/Unit/MSFT_ADReadOnlyDomainControllerAccount.Tests.ps1` line 88 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44uz6c7ntMB5Mtq0sP:-O4F7UjE2A5QVEoAOwic:b-kmdgeo) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/tests/Unit/MSFT_ADReadOnlyDomainControllerAccount.Tests.ps1#L88)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Not my code - and my Pester knowledge is quite limited - but I think it just reflects the other Contexts in Set and Test so maybe keep for symmetry if nothing else?
</blockquote></details>

Would have most likely been for symmetry - which I can understand. But it makes the length of the test messages longer and may also lead to confusion (e.g., where are the get tests when the system is not in the desired state).

Happy to leave as is.
___
*[`source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/en-US/about_ADReadOnlyDomainControllerAccount.help.txt` line 34 at r6](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-O44rGil9IyibNAMpfDK:-O4F1dGK9ftYsxot2UBU:b-tndx70) ([raw file](https://github.com/dsccommunity/ActiveDirectoryDsc/blob/d70604aefdcf9e678ee6bea0ac9c686850b3413a/source/DSCResources/MSFT_ADReadOnlyDomainControllerAccount/en-US/about_ADReadOnlyDomainControllerAccount.help.txt#L34)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Sorry - don't follow? Ensure is a supported read only attribute?
</blockquote></details>

Sorry, I didn't notice the `read` and because the README.txt mentioned that the resource can't be used to remove the account, I thought it was a mistake - but understand it is retained to return current state.

Sidenote: I think the name `ensure` for this type of parameter (where it is only used to return the state... not `ensure` it is actually in a given state) doesn't really make sense.


<!-- Sent from Reviewable.io -->

2024-08-14 09:18 UTC, PlagueHO reviewed
@johlju - <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

If you're happy to merge, can you approve the changes?

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-:-O4FAPYm0YbuCaHc6Ipv:baicefc)* status: all files reviewed, 3 unresolved discussions (waiting on @Borgquite and @johlju)



<!-- Sent from Reviewable.io -->

2024-08-18 11:28 UTC, johlju approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I you all are happy, I'm happy. :slightly_smiling_face:  Thank for helping review @PlagueHO! 

> Reviewed 1 of 1 files at r6, 12 of 12 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/ActiveDirectoryDsc/713#-:-O4_E_mz4ndSAnFNSE4B:b-sboqk7)* status: all files reviewed, 2 unresolved discussions (waiting on @Borgquite)



<!-- Sent from Reviewable.io -->

2024-08-18 11:31 UTC, merged